### ISSUE TITLE
Reasonable handler for unversioned/ill-versioned RSS feeds

### ISSUE THREAD

**Issue by kzn** [rometools/rome#186]
Currently, when ROME tries to parse RSS feed it tries different parsers based on version attribute of rss tag, but some feed don't provide one, or provide some non-standard version. 

May be add some reasonable default parser for that kind of feeds. Assuming for example, if the version of the feed couldn't be determined, then try the parser for latest version?

**Comment by PatrickGotthard** [comment]
Hi @kzn,

ROME was designed not to handle broken feeds. I don't know whether we really should implement such a fallback mechanism.

When we implement such a functionality it should not be enabled by default. Either the user has to handle such errors explicitly or to enable this mechanism with a setting, configuration flag or something else.

Regards,
Patrick

**Comment by mishako** [comment]
@PatrickGotthard
> ROME was designed not to handle broken feeds.

I'm inclined to disagree. Some parts of Rome have intentionally been designed to handle brokenness. Namely `XmlReader` is lenient by default happily accepting a file with UTF-8 BOM followed by `<?xml encoding="{insert your favorite encoding}"`. Another such part is Rome's `DateParser` which accepts ISO 8601 in spite of what the RSS spec says.

In general I think Rome should be as lenient as possible, because our users usually have no control over the feeds they parse. Unlike databases or compilers where the user has no excuse to keep things broken.

**Comment by kzn** [comment]
I think that the state of RSS is a bit similar to the HTML. There is a huge number of html pages that doensn't conform to the standard. Neverless, the browsers are able to handle them and show to the user.

I had similar experience with RSS feeds. Some of them are perfectly handled by RSS readers, while wouldn't parse with ROME.
I think that ROME should be able to handle broken feeds, with reasonable limits, of course. For example, as tagsoup/jsoup libraries handle HTML pages. Otherwise the user will be urged to dig into RSS/ATOM standards to fix broken feeds and IMHO that is comparable with writing custom RSS parser.

**Comment by ChristianBusch** [comment]
Imho ROME should be as lenient as possible for the reasons @mishako and @kzn stated.

I'd rather have ROME extract as much information as possible out of a feed instead of giving up, or even withholding information it *could* parse but decides not to because the feed does not conform to the standard.

If you want to make a user aware of a broken feed I'd prefer it's done in a way, that still allows parsing.

**Comment by mishako** [comment]
@PatrickGotthard Any thoughts?

**Comment by mishako** [comment]
This is now partially fixed by #274. I say partially because the fix doesn't cover feeds with an incorrect version. Anyway, it's something.

**Comment by mishako** [comment]
@kzn Rome 1.6.0 has been released with this issue fixed (or, as I said earlier, partially fixed).
