### ISSUE TITLE
Field "rating" not supported!?

### ISSUE THREAD

**Issue by UltimateFighter** [rometools/rome#187]
is the rss 2.0 field "rating" nnot supported by rome yet?

**Comment by mishako** [comment]
@UltimateFighter No, it's not supported. Could you please elaborate on why you need it and how you're going to use it? Do you have an example of a feed that has rating field set? I'm asking because RSS specification restricts rating field to PICS format, which in turn has been superseded by POWDER (six years ago).

**Comment by mishako** [comment]
Closing this. Please speak up if you disagree.
