### ISSUE TITLE
Potential "duplicate" dc:date element

### ISSUE THREAD

**Issue by josh-cain** [rometools/rome#196]
In the RSS 2.0 feed, setting a publishedDate will also populate the dc:date element.  This won't validate against the W3C validator found here: http://validator.w3.org/feed/check.cgi.

An easy solution for this would be to just add a publishedDate to the SyndFeedImpl, but I'm not sure how that would affect existing implementations.  Alternatively, could just provide another implementation with more verbose fields.  More information here: http://stackoverflow.com/questions/13300903/valid-rss-2-0-using-rome/27699338#27699338

Let me know what direction seems best and I'll put together a pull request - I'd like to get involved on this one!

**Comment by PatrickGotthard** [comment]
@snoopdave @farrukhnajmi @imk what do you think?

**Comment by metellusa** [comment]
Hi! Have you ever gotten that <dc:date> tag out of your feed? I tried to follow the recommendation of the stackoverflow article but it did not work for me.

**Comment by cainj13** [comment]
I did, I'll put together a pull request this week with the modified class that allowed me to get it out.

**Comment by mishako** [comment]
I don't think W3C validation is of a high priority for us. Of course Rome-generated feeds should follow the specifications. However not every rule in the W3C validator comes from the specifications. And some of them are arguably not really important.

Anyway looks like this issue can't be fixed in a backwards compatible manner. So it has to be postponed till the next major version. Same goes for #147.

**Comment by PatrickGotthard** [comment]
Clo
