### ISSUE TITLE
Support for multiple plugins with custom properties files locations

### ISSUE THREAD

**Issue by brianmacdonald** [rometools/rome#208]
The current plugin architecture has a limitation of only supporting two property file locations:
  - com/rometools/rome/rome.properties - Master
  - rome.properties - Plugin. Overrides Master

This creates a problem when trying to use multiple plugins jars as the last rome.properties in the classpath overrides the all of the other property files. 

Here is an example:
First the Rome jar is loaded in classpath with the primary properties file. Next a custom media parser plugin loads with its properties file. Finally Rome Modules jar is loaded overriding all other properties.

While changing the classpath order is possible it can be a nontrivial task in existing projects.

One solution is to allow for multiple custom properties files to be loaded after rome.properties. These properties files location might be defined in a method of configuration like environment variables

**Comment by mishako** [comment]
Multiple rome.properties from different jars don't override each other. They get merged by `PropertiesLoader` class, which uses `Classloader::getResources` to find all rome.properties on the classpath.

So this should not be a problem, unless:
 * you shade your jar with maven-shade-plugin. The plugin puts all resource files in the same jar, so files with the same name overwrite each other. The options you have are either to stop shading (which I think is a good idea anyway), or to configure the plugin to exclude all rome.properties except for the one you control and where you can configure everything you need.
 * you do want to override rome.properties from another jar. Unfortunately it's not easily achievable, because Rome's `PropertiesLoader` considers properties to be append-only. The solution would be to somehow remove all rome.properties from the classpath except for the one you control.

**Comment by mishako** [comment]
@brianmacdonald Any thoughts?

**Comment by mishako** [comment]
Closing this. Please let me know if it's still an issue.
