### ISSUE TITLE
Combine all ROME projects in one repository

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#217]
Currently all ROME projects have their own repository. As a consequence:
- creating new releases is difficult, because every project has to be build seperately and in the correct order
- contributing to ROME is not as easy as it could be - you have to check out different repositories to develop for ROME
- using services like Travis CI is not possible due to snapshot dependencies that can't be resolved
- managing issues that affect multiple projects is difficult

I propose to combine all projects to solve this issues. 

I don't know whether it's better to combine all projects in this repository because it has the most forks of all or in a completely new repository.

Before performing the migration we should merge as many pull requests as possible and reduce the numbers of branches to an absolutely minimum. In addition we should try to inform all users that have forked any of our projects.

What do you think @mishako @imk @snoopdave @farrukhnajmi?

**Comment by mishako** [comment]
Exciting!

I think we should reuse `rome` repository because it has most stars and forks if nothing else.

Regaring currently open pull requests, I will take care of OSGi ones and [Support CP1047 encoding](https://github.com/rometools/rome/pull/215). If no one opposes I will just merge them in a week or something. [Http URL Redirect check](https://github.com/rometools/rome/pull/211) is not a huge change and can be easily rebased or recreated. Not sure what to do with [Central Banking Module
](https://github.com/rometools/rome/pull/199) and [Fix in OPML](https://github.com/rometools/rome-opml/pull/4).

All the branches can be just killed I think. Not sure what to do with `gh-pages` though.

Project's [network graph](https://github.com/rometools/rome/network) is a good place to look for forks that are actually being worked on. I can do that.

You probably already knew it, but it's possible to merge repositories and keep the git history:
http://stackoverflow.com/questions/13040958/merge-two-git-repositories-without-breaking-file-history

Also for the combined repo I would suggest following folder structure:
```
certiorem/
certiorem-webapp/
core/
fetcher/
modules/
opml/
propono/
utils/
pom.xml
```

**Comment by PatrickGotthard** [comment]
I've looked at all repositories. We should check whether some branches contain enhancements that were not merged into the master.

I just merged the CP1047 fix. For the other enhancements I propose to generate diffs that can be applied after merge.

The gh-pages should be generated by Maven from src/site when I remember correctly.

I already used the instructions of the StackOverflow thread some while ago at work, but I don't remember what happened to the tags. Do you know whether it is possible to migrate the tags?

Another thing I would propose -> we should name the project folders exactly like the artifactIds. I've never seen someone "removing the project prefix" and I've never tested it but maybe also Maven has a problem with folders names that doesn't match the module name / artifactId.

In addition all ROME projects will be displayed as a block when you check ROME out in your IDE among other projects.

After combining all projects I would propose to update all 3rd Party libs (e.g. Apache HttpClient and JDom) and to publish ROME 1.6.0.

**Comment by mishako** [comment]
> For the other enhancements I propose to generate diffs that can be applied after merge.

:+1: 

> Do you know whether it is possible to migrate the tags?

I don't think it's possible in our case. A tag can point only to one commit. If I correctly understand the merging procedure, we will end up with 9 different commits for each of the releases (1.5.0 and 1.5.1).

> we should name the project folders exactly like the artifactIds.

:+1: 

> and to publish ROME 1.6.0.

I would like to fit a couple more fixes in 1.6.0, namely https://github.com/rometools/rome/issues/186 and classloader fallback I mentioned in https://github.com/rometools/rome/pull/216.

**Comment by PatrickGotthard** [comment]
Just another note: we should create a compressed archive of every single repository. So we will be able reproduce older versions when it should ever be required (e.g. some time ago someone asked for the sources of v1.0).

**Comment by PatrickGotthard** [comment]
I just cleaned up all branches. I was able to delete most of them but rome-modules does have two branches with changes that are not yet merged into the master branch. The fastest solution would be to create diffs for them.

**Comment by mishako** [comment]
@arankin @nkiesel @FBergeron @kzn @cainj13 @alabeduarte @freemarmoset @ahirsh @nea @blop @buckett @dipacs @mihxil @svenwiegand @vchimishuk @travisfw
Hi folks! I'm mentioning you all because you have forked one of the Rome repositories. We would like to inform you that all of the Rome repositories are going to be combined into a single one. If you plan to bring your changes back to the upstream (I hope you do), you'll need to do a rebase against upstream master. Those of you who have forked Rome sub-projects (e.g. rome-modules or rome-fetcher) will need to change the upstream remote to rometools/rome. Thank you for your contributions!

**Comment by mishako** [comment]
@PatrickGotthard Any progress on this? Can I help?

**Comment by PatrickGotthard** [comment]
Hi mishako,

currently I have no time to do this. It would be really helpful when you write a simple application that copies the issues from one project to another. GitHub provides a good REST API that can be used for this purpose.

After that we can disable the issue trackers of the other projects. Maybe we should also update the Readme files temporarily to inform the users about the new location.

Regards,
Patrick

**Comment by mishako** [comment]
@PatrickGotthard I copied all the issues (both open and closed) to the `rome` repo. I didn't touch issues in `rome-certiorem` though, because they are very much unrelated to Rome and I think we should just kill the module anyway after the merge.

I don't have access to disable issue trackers. I guess one has to be an administrator or something.

**Comment by PatrickGotthard** [comment]
Hi mishako,

I've just disabled the issue trackers of all other projects. Thanks for your support!

When you have enough time it would be really great when you prepare a script that combines all repositories into one. 

Currently I'm trying to work with the computer as sparse as I can because I'm facing some dizziness since a few weeks especially when I'm working with the computer :(

Regards,
Patrick

**Comment by pubmikeb** [comment]
First of all, thanks for the great and well-working project!

Regarding repositories, there are multiple repositories, which can confuse new user, for instance,

- http://rometools.github.io/rome/ with the ROME 1.0 version
- https://github.com/rometools/rome with the ROME 1.5.1
- http://mvnrepository.com/artifact/rome
- http://mvnrepository.com/artifact/com.rometools/rome

which of them should I use?
Please, consider arranging & sync all these repositories.

One more moment, http://mvnrepository.com/artifact/com.rometools/rome/1.5.1 is depending on `slf4j-api` 1.7.7 and `jdom` 2.0.2, while there are already 1.7.16 and 2.0.6 respectively with a lot of bug fixes. Is it possible to update ROME's dependency list in order to be able automatically update sub-modules?

Thanks.

Best regards,
Mike

**Comment by PatrickGotthard** [comment]
Hi pubmikeb,

this isn't the right thread to discuss such things, but I'll answer anyway.

- http://rometools.github.io/rome/ is the documentation of our project. Unfortunately it is really outdated, we are working on it.
- https://github.com/rometools/rome is this repository.
- http://mvnrepository.com/artifact/rome this is some kind of mirror for Maven Central (which you forgot on your list). The URL points to the old versions of ROME
- http://mvnrepository.com/artifact/com.rometools/rome look at the previous point. The url points to the new versions of ROME.

There are even more places on the web where you can find old sourcecodes and docs of rome. This is a historically problem that we cannot solve because we don't have access to the old pages. 

This is a summary of the official sources:
- Latest sourcecode: https://github.com/rometools/rome
- Latest versions: http://search.maven.org/#search%7Cga%7C1%7Crometools
- Official (but currently outdated) documentation: http://rometools.github.io/rome/

To answer you question about slf4j and jdom: of course we will publish new versions with updated dependencies in the future. In the meantime you have to declare updated versions yourself (regardless which build tool you use).

Regards,
Patrick

**Comment by PatrickGotthard** [comment]
Hi mishako,

your changes seem to be okay. @snoopdave @imk @farrukhnajmi would you look at the pull request too? https://github.com/rometools/rome/pull/265

Regards + many thanks @mishako !
Patrick

**Comment by pubmikeb** [comment]
Thanks Patrick for the detailed explanation.

One more question, is there any updated release road map for ROME tools?
BTW, does ROME have some group/thread where people can ask such kind of questions?

P. S. Feel free to move my posts to more convient thread/space.
