### ISSUE TITLE
Typo in rometools.github.io/rome/HowRomeWorks

### ISSUE THREAD

**Issue by SimonLammer** [rometools/rome#271]
Under the segment "

> Notes on the Rome parsing process

is a paragraph

> Rome is based around an idealized and abstract model of a Newsfeed or "Syndication Feed." Rome can parse any format of Newsfeed, including RSS variants and Atom, into this model. Rome can convert from model representation to any of the same **Newfeed** output formats.

I'd imagine "Newfeed" should be "Newsfeed".

**Comment by mishako** [comment]
Thank you for the finding Simon. That is undoubtedly a typo. However I think we should not fix it, because this text is a copy of Dave's blog post. I think we shouldn't alter it in any way. Although we probably want to replace it with more up to date documentation. That's something I think we should really focus our efforts on.
