### ISSUE TITLE
CDATA sections being escaped

### ISSUE THREAD

**Issue by janih** [rometools/rome#280]
Should the CDATA sections not be escaped? The following code results otherwise:

```
    SyndFeed feed = new SyndFeedImpl();
    feed.setFeedType("rss_2.0");
    feed.setTitle("title");
    feed.setLink("http://localhost/feed");
    feed.setDescription("description");

    SyndEntry entry = new SyndEntryImpl();
    entry.setTitle("entry title");
    entry.setUri("http://localhost/feed/item1");
    entry.setLink("<![CDATA[http://localhost/feed/item1]]>");

    SyndContent entryContent = new SyndContentImpl();
    entryContent.setValue("<![CDATA[<p>test</p><p>test</p>]]>");
    entry.getContents().add(entryContent);
    feed.getEntries().add(entry);

    SyndFeedOutput output = new SyndFeedOutput();
    System.out.println(output.outputString(feed));
```

Output:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
  <channel>
    <title>title</title>
    <link>http://localhost/feed</link>
    <description>description</description>
    <item>
      <title>entry title</title>
      <link>&lt;![CDATA[http://localhost/feed/item1]]&gt;</link>
      <content:encoded>&lt;![CDATA[&lt;p&gt;test&lt;/p&gt;&lt;p&gt;test&lt;/p&gt;]]&gt;</content:encoded>
      <guid isPermaLink="false">http://localhost/feed/item1</guid>
    </item>
  </channel>
</rss>
```

I've tried Rome versions 1.0 and 1.5.1 but the results are similar. I've also tried different modes (xml, html) for content. Am I missing some setting here?

**Comment by mishako** [comment]
Hei Jani. Thank you for raising the question. This looks like an expected behavior to me. The right way to do what you want is to not use CDATA:
```java
entry.setLink("http://localhost/feed/item1");
entryContent.setValue("<p>test</p><p>test</p>");
```

**Comment by janih** [comment]
My example works well without CDATA, but if one uses CDATA section it should not be escaped? There was this old issue, that might be related: #134 

Currently, is it possible to create this kind of xml with rometools:

    <?xml version="1.0" encoding="UTF-8"?>
    <rss xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    	<channel>
    		<title>title</title>
    		<link>http://localhost/feed</link>
    		<description>description</description>
    		<item>
    			<title>Title of Feed Item</title>
    			<link>/mylink/article1</link>
    			<description>
        <![CDATA[
          <p>
          <a href="/mylink/article1"><img style="float: left; margin-right: 5px;" height="80" src="/mylink/image" alt=""/></a>
          Author Names
          <br/><em>Date</em>
          <br/>Paragraph of text describing the article to be displayed</p>
        ]]>
      </description>
    		</item>
    	</channel>
    </rss>

**Comment by mishako** [comment]
> if one uses CDATA section it should not be escaped?

CDATA should be escaped like any other text. Consider this example:
```java
feed.setDescription("This is how you use CDATA: <![CDATA[<b>not bold text</b>]]>");
```

If Rome did not escape CDATA, how would it know that the desired output is `This is how you use CDATA: <![CDATA[<b>not bold text</b>]]>` and not `This is how you use CDATA: <b>not bold text</b>`?

> There was this old issue, that might be related: #134

That issue is about reading XML, not writing.

> Currently, is it possible to create this kind of xml with rometools:

No, it's not possible. Mainly because of the uncertainty I described above. Also, the article on Wikipedia [1] has some additional arguments against programmatically generated CDATA sections.

[1] https://en.wikipedia.org/wiki/CDATA

**Comment by janih** [comment]
Ok, thank you mishako for the explanation. I can close this issue.

**Comment by scythepl** [comment]
@mishako 
CDATA sections should not be escaped. What's the point of CDATA sections if their content is exactly the same as if there wasn't CDATA at all? 
It is specified here: https://www.w3.org/TR/REC-xml/#sec-cdata-sect , you might want to take a look at this discussion at stackoverflow:
http://stackoverflow.com/questions/223652/is-there-a-way-to-escape-a-cdata-end-token-in-xml

**Comment by mishako** [comment]
@scythepl Hello! Thanks for raising the question!

While I believe that the stackoverflow discussion you linked is not relevant neither to this issue, nor to Rome in general, I think there is a high chance of us diving too deep into complicated abstract questions and not finding any answers.

Instead I would like to suggest starting from the other end. Imagine you're writing Rome. And you have a method `feed.setDescription()`. What should be the result of this call? How should the resulting XML look?
```java
feed.setDescription("This is how you use CDATA: <![CDATA[<b>not bold text</b>]]>");
```

**Comment by scythepl** [comment]
@mishako The question is exactly about our case. I can't stress this enough: right now, ROME provides an INVALID implementation of handling output of CDATA section, not implementing the w3c's "Extensible Markup Language (XML) 1.0 (Fifth Edition)". The resulting xml should be:

<description>
<![CDATA[This is how you use CDATA: <![CDATA[<b>not bold text</b>]]]]><![CDATA[>]]> 
</description>

which is a direct result of using the rule

[20]   	CData	   ::=   	(Char* - (Char* ']]>' Char*))

from the documentation https://www.w3.org/TR/REC-xml/#sec-cdata-sect

A similar expression using CDATA section itself is shown in this answer in the thread I posted: http://stackoverflow.com/a/223782/1961634

**Comment by mishako** [comment]
Let me check if I understand you. This is the resulting XML you suggested:
```
<![CDATA[This is how you use CDATA: <![CDATA[<b>not bold text</b>]]]]><![CDATA[>]]> 
```
This is what Rome currently produces:
```
This is how you use CDATA: &lt;![CDATA[&lt;b&gt;not bold text&lt;/b&gt;]]&gt;
```
And you think that the latter is invalid because it doesn't conform to the XML standard?

**Comment by mishako** [comment]
> Rome's current output is valid XML, but it is invalid CDATA

What do you mean when you say "invalid CDATA"? Do you mean that if you put it inside of a CDATA section it will become invalid XML? There are no CDATA sections in the Rome's output, so I have hard time understanding how it can be an "invalid CDATA".

**Comment by scythepl** [comment]
Because it is not a cdata section at all. It is standard xml content, not a cdata. The moment you escape cdata  start tag, it stops being a cdata section.
Let's look at it from the other side - how can you generate a valid <![CDATA[ section in rome's output?

**Comment by mishako** [comment]
I agree that it's not a CDATA section at all. Does it need to be? Good point, you can't generate a CDATA section using Rome. Any attempts to output CDATA will result in a simple plain text, because Rome escapes the output. Do you think it's a problem that in Rome you can't generate CDATA?

**Comment by scythepl** [comment]
I'm glad we've finally understood each other:) For me it's a problem. I have a strict RSS specification to adhere to and it requires the usage of "real" CDATA section. Rome's great, good API, easy to use, reliable and well tested and I'd really like to use it. Without that option, I can't.
It would be easy to include in API, just add SyndContent.setCdata(boolean), or even SyndContent.setValue(String, boolean).

**Comment by mishako** [comment]
> I have a strict RSS specification to adhere to and it requires the usage of "real" CDATA section.

Does it? I can't find any mentions of CDATA in the RSS 2.0 specification: http://cyber.harvard.edu/rss/rss.html

**Comment by scythepl** [comment]
It does mention it, though not explicitely:

> RSS is a dialect of XML. All RSS files must conform to the XML 1.0 specification, as published on the World Wide Web Consortium (W3C) website.

Therefore, a library with full RSS support should cover reading and writing cdata sections as they are a part of XML 1.0 specification.

**Comment by mishako** [comment]
Let me check again that I understand you. This is what the RSS spec says:

> RSS files must conform to the XML 1.0 specification

And from that you conclude that an RSS library should include support for everything that is a part of the XML 1.0 specification?

**Comment by scythepl** [comment]
There's no *must* in open source, but the most popular and possibly best RSS library definitely *should*. Whether it's a feature request or a bug I'm not sure. Will rome properly read a real cdata section? I haven't checked.

**Comment by mishako** [comment]
These features are also a part of the XML spec:

- Processing Instructions
- Custom versions
- Custom encodings
- DTD
- xml:lang
- Comments
- Empty tags

Do you think Rome should support all of them?

**Comment by janih** [comment]
Regarding supporting all of XML spec, certainly not all is needed, but CDATA -sections seem to be quite popular in rss feeds. The [example I posted](https://github.com/rometools/rome/issues/280#issuecomment-197739172) is not uncommon.

**Comment by mishako** [comment]
@janih The argument is about generating XML, not reading. Rome supports CDATA in the input.

**Comment by scythepl** [comment]
@mishako This discussion seems to be going nowehere. Please consider the topic of rome being able to generate a valid CDATA section a feature request. I could start a new issue if it is needed.

**Comment by mishako** [comment]
@scythepl It's unfortunate that you think that the discussion is going nowhere. I was just trying to understand your reasoning. It's impossible to make decisions on features without understanding the needs and motives.

The discussion was actually almost over. I asked if Rome should support all XML features. Next, you would say "no, it should not". Next, I would ask "what is so special about CDATA then?". And you would answer "unlike other XML features, it is important to be able to generate CDATA because [...]". Then I and everyone else would know why we need this feature. But now you're unwilling to continue the discussion and I can't read your thoughts.

Would you consider answering one more question? It would tremendously help to know the answer. You said before:

> I have a project, in which (I have examples with such syntax) I have to use CDATA.

Why do you _have_ to use CDATA in your project? What exactly imposes this requirement? What is the use case? Please answer in detail. A lot depends on you answer. For example, the feature request is less likely to be considered if the use case will seem very rare. The implementation also greatly depends on the use case.

**Comment by scythepl** [comment]
I think that discussion is going nowhere, because you seem to be taking it personally and, maybe I am wrong, you seem to be angry, irritated, maddened somehow by it for reasons I can not understand.

As for the project: it's an implementation of ACER REMIT notifications using RSS feed. It is an official UE institution which standardizes certain information sharing protocols. The reference examples provided in the documentation for those notifications contain unescaped, valid CDATA sections as defined in the XML documentation I mentioned.  A fragment:

```
<description> 
<![CDATA[ <?xml version="1.0" encoding="UTF-8"?> <ns1:REMITUrgentMarketMessages
...
</ns1:REMITUrgentMarketMessages> ]]> 
</description> 
```

**Comment by mishako** [comment]
In the "REMIT guidance on the implementation of web feeds" [1] they say:

> It is expected to include within the CDATA declaration of the “description”//”summary” fields a valid XML that will contain the inside information relevant to the specific feed update.

It's unclear whether they expect CDATA because that's how their systems are implemented, or because they just didn't consider that XML has other ways of achieving the same result. I would be very surprised if their systems can't handle ordinarily escaped text, because that would mean that they wrote their own XML parser instead of using literally any existing XML library.

I think the best course of action is to contact ACER and ask them if instead of the above fragment their system can accept this:
 ```
<description> 
&lt;?xml version="1.0" encoding="UTF-8"?&gt; &lt;ns1:REMITUrgentMarketMessages
...
&lt;/ns1:REMITUrgentMarketMessages&gt; 
</description>
```

Most likely they will either say yes, or suggest that you can try and see how it goes. If in the end it doesn't work, you can use jdom library (which Rome is shipped with) to post-process generated XML. Should be as simple as:

`element.setContent(new CDATA(element.getText()));`

It's kind of a hack, but I think it's an adequate solution to this very specific requirement.

If in the end you still think that Rome should have support for generating CDATA, please file a new issue. Although I think that ACER's inability to handle valid XML doesn't warrant adding a new feature to Rome, I don't own Rome and I don't decide. Rome has many contributors, so if you believe that this is important and needed, please continue pushing for the change.

[1] https://www.acer-remit.eu/portal/document-download?documentId=t724lj327ox
(the link triggers a download)

**Comment by Artgit** [comment]
Hello, how about the following: 

> cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt - An item may also be complete in itself, if so, the description contains the text (entity-encoded HTML is allowed; see examples) https://cyber.harvard.edu/rss/rss.html#hrelementsOfLtitemgt

**Comment by mishako** [comment]
@Artgit @krystiankaluzny Makes sense, but how does it relate to Rome not being able to produce cdata sections?
