### ISSUE TITLE
Possible packaging issue with Gradle on Android

### ISSUE THREAD

**Issue by mr** [rometools/rome#316]
I'm trying to use ROME in an Android app, including the MediaRSS extension. I've tried including `compile 'com.rometools:rome-modules:1.7.0`, however I get this error when compiling:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForBetaDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK rome-utils-1.7.0.jar
  	File1: /Users/mattro/.gradle/caches/modules-2/files-2.1/com.rometools/rome/1.7.0/30445daf75f01366e76a9c97ad3993839bedfd33/rome-1.7.0.jar
  	File2: /Users/mattro/.gradle/caches/modules-2/files-2.1/com.rometools/rome-modules/1.7.0/4712d0e53c08d964c4e2e9246c31dbc93de78d66/rome-modules-1.7.0.jar
```

1.5.0 seems to work, but it doesn't have the features I need. Any suggestions?

**Comment by mishako** [comment]
So, the reason why this happens is because both `rome-1.7.0.jar` and `rome-modules-1.7.0.jar` have `rome-utils-1.7.0.jar` embedded inside them. This is done to ease usage of Rome in OSGi environments (see #216 for details). For non-OSGi use cases embedding a jar doesn't make a difference, it's ignored and instead `pom.xml` is used to load dependencies.

The problem is that android build system is strict about duplicate files. The solution is to force it to ignore or exclude the duplicates. Stackoverflow [suggests](https://stackoverflow.com/questions/20673625/android-gradle-plugin-0-7-0-duplicate-files-during-packaging-of-apk) doing something like this:
```
android.packagingOptions {
    exclude 'rome-utils-*.jar'
}
```

I haven't tested it though, so let me know if works.

**Comment by mr** [comment]
Thanks! That worked.
