### ISSUE TITLE
Get raw xml or convert it to json

### ISSUE THREAD

**Issue by frangarcia** [rometools/rome#324]
I am currently using Rome to ingest some content from rss and atom sources but I would like to keep as well the raw xml or even better, convert the source into a json format. I am struggling to do that and I was wondering if there is already something around this area. Any ideas?

**Comment by mishako** [comment]
To get raw XML you can fetch and store it in a variable before passing it to Rome. Converting arbitrary XML to JSON is not entirely trivial, but I guess it's possible that there are libraries for that.

I think stackoverflow.com is a better place for this kind of questions. Not because we don't want you to ask questions here. It's just that there is a lot more people there and it's more likely that you will get the answers you're looking for.
