### ISSUE TITLE
Android placement of rome.properties

### ISSUE THREAD

**Issue by joaoBeno** [rometools/rome#335]
Hello there folks... So, I need to parse some feeds, but the pubDate is formated as: `dd MMM yyyy HH:mm:ss Z // Ex: 19 May 2017 02:00:00 -0300`, and I can't get ROME to parse it. I read on issue #317 that I need to set the mask at rome.properties. The problem is that the file doesn't work, no matter where I place it within the project!

I posted the question here because I think it may help other people...

**Comment by mishako** [comment]
Hi João! Sorry for the delay. I don't know much about Android, but the way Rome loads `rome.properties` is very simple and should work in similar way on all platforms.

The code is a bit complicated (https://github.com/rometools/rome/blob/master/rome/src/main/java/com/rometools/rome/io/impl/PropertiesLoader.java), but basically it looks for `rome.properties` on the classpath (actually on the classpath of the `ConfigurableClassLoader` class). Which usually is `src/main/resources`, but might be something else on Android? You can test if your file is in the right place by running something like this:
`ConfigurableClassLoader.INSTANCE.getClassLoader().getResources("rome.properties")`

**Comment by mishako** [comment]
Any updates?

**Comment by Huangbin1234** [comment]
just for Android  Project，There is a solution here:
1、Modify the source code。

final InputStream is = classLoader.getResourceAsStream(masterFileLocation);
----replace -----
final InputStream is = 	ProjectApplication.getApplication().getResources().getAssets().open(masterFileLocation);

2、Copy the “rome.properties” into the “assets” folder

**Comment by adelinolobao** [comment]
Hi @Huangbin1234 

Thank you for your response, but I don't understand how can your explanation helps us with the issue reported.

For example, if you have this snippet of code where a feed is loaded from a url

```
final XmlReader xmlReader = new XmlReader(new URL(url));
final SyndFeed syndFeed = new SyndFeedInput().build(xmlReader); 
```

There is no away that we can initialize our XmlReader or SyndFeed with the properties from your assests. Right?

**Comment by Huangbin1234** [comment]
@adelinolobao 
Android project properties file "rome.properties" placed in the location and java se project location is different, so read the way is different, android project placed in the  "app\src\main\assets\rome.properties" folder,   read through the system API  , for example: context.getResources (). GetAssets (). Open (fileName).
I just modified the "PropertiesLoader.class" 90 lines in the constructor () ,change the way files are read ,to help the android project to recognize.
ProjectApplication.getApplication () refers to the context of the android project,you can do it yourself.

Summary: Because the resource file path storage location is different, so the need to use android way to read "app \ src \ main \ assets" folder under the configuration file.
Perhaps this is not the best way, but in the android project is able to solve the problem.

**Comment by adelinolobao** [comment]
Hi @Huangbin1234 

Thank you for the reply, now I understand what you are saying. 
Basically you are cloning or importing to your project the rometools and modifying the class loader. That is a solution but it kinda breaks the maintainability of the project itself since every update from rometools team you need to update your project with the changes.

@mishako I would like to understand if there is any idea in the roadmap of rometools to allow the developers to provide these rome.properties via constructor instead of hardcoded the path loader into the library itself.

**Comment by imk** [comment]
I think, the way parsers are implemented in Rome at the moment, it would be very hard to transfer properties from an instance to the required places. This change would probably break existing modules. So IMHO that could be a feature for Rome 2.0 - but it would make sense having better control over custom configuration.

**Comment by joaoBeno** [comment]
Hello there, sorry for taking too long for posting this.

I solved the issue by creating a folder "resources" at `app/src/main`, and added `rome.properties` there. then, at the app `build.gradle` I added the following:

````
sourceSets {
    main {
        resources {
            srcDirs "src/main/resources"
        }
    }
}
````

That was it! After I put that, Rome parsed my dates correctly... The trick was finding an SO question where someone discussed how to place a file on an arbitrary path inside the APK package.

I hope this help other people!

**Comment by mishako** [comment]
@Huangbin1234 @adelinolobao Does João's solution work for you?

**Comment by adelinolobao** [comment]
@mishako yes for me it works ;) thanks for sharing the solution

**Comment by mishako** [comment]
Great! Closing the ticket then.
