### ISSUE TITLE
Missing elements in GoogleBaseModule

### ISSUE THREAD

**Issue by imk** [rometools/rome#362]
There are some elements missing in google base module, see https://support.google.com/merchants/answer/7052112

**Comment by gokhanakgul** [comment]
I am going to try to implement missing parts of it.

**Comment by gokhanakgul** [comment]
Hi 
I prepared first plan to do following items abide by the documentation of google merchant. 

1. Add URL imageLink attribute instead of URL[] imageLinks 
Convert URL[] imageLinks to URL[] additionalImageLinks

Details : https://support.google.com/merchants/answer/6324350

2. New interface Offer 
    availability  (Required)
    availabilityDate  (Optional)

3. Product interface new Attributes
    googleProductCategory
    gtin
    mpn

**Comment by PatrickGotthard** [comment]
Due to the lack of active developers I'll close this issue for now.
