### ISSUE TITLE
High allocation rate due to object nesting

### ISSUE THREAD

**Issue by raphw** [rometools/rome#401]
Hi, thanks for the project first and foremost! I made an observation when debugging a potential memory leak. I am reading an Atom feed and I am buffering up to five pages while another page is processed and sent to the database. These six pages with 1000 elements each cause the allocation of almost one million objects! Their size is not too big, all in all, the retained size is only about 60 MB but it causes quite some work for the young GC.

A large fraction of the allocations stem from `ObjectBean`, `EqualsBean` etc. Do you think it would be possible to refactor those instances to static dispatchers? This would reduce the problem significantly.

Thanks!

**Comment by mishako** [comment]
Hi Rafael! Thank you for the suggestion. It sounds very reasonable. If you have an idea on how to fox it you can try submitting a PR with a fix. Otherwise I can look into it (probably not earlier than late December though).

**Comment by raphw** [comment]
I will try to submit a PR, I am bit drowning on issues in my own project these days but we are using ROME, I will keep it in the back of my head for a slow week!

**Comment by raphw** [comment]
I prepared a PR, I will send it over tonight. It reduces the average allocation rate of Rome to 27% of today's rate!

**Comment by runt9** [comment]
I appreciate this issue being resolved, however an upgrade path was not provided from previous versions. In any situation that any of these objects are serialized before upgrade and deserialized after upgrade, a failure occurs as CloneableBean does not exist in the prior version.

As a better example, when using Spring Integration and using SyndEntry as the message type, Spring will use default Java serialization to serialize the SyndEntryImpl object. If you stop the app with messages in the queue on a version prior to 1.12.0, upgrade the app to ROME > 1.12.0, then start the app back up, deserialization fails with the following underlying error:

```
nested exception is java.io.InvalidClassException: com.rometools.rome.feed.impl.CloneableBean; class invalid for deserialization
```

In addition, it's a Serializable object but the SerialVersionUID was set at `1L` both before and after the upgrade, so it was much harder to debug the issue because proper Java serialization techniques weren't followed. It should be throwing a differing version error rather than an invalid class error.

Again, I see the changes in this issue as being very positive, but an upgrade path is needed. I don't have thoughts on the best way to handle this right this second, but I will revisit this with solution ideas and potentially a PR if I can come up with a good way to handle this.

**Comment by raphw** [comment]
I did not even think of tjis, to fully admit it. I'd think anybody would serialize Atom to XML and missed the interface completely. This should be solvable easily by implementing readObject methods.
