### ISSUE TITLE
Unable to parse date with format yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'

### ISSUE THREAD

**Issue by AbtinZohrabi** [rometools/rome#411]
This format can be added to default list maks located in DateParser class

**Comment by mishako** [comment]
Hi! I'm curious about the `SSSSSSSSS` part of your date format. According to [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) class documentation `S` stands for "Millisecond". I think your format implies possibility of the number of milliseconds being as high as `999,999,999` which corresponds to more than 11 days. I don't think there is a way to unambiguously represent more than 999 milliseconds in a date-time format.

The answer to this Stackoverflow question seems to support my point: https://stackoverflow.com/questions/44000755/yyyy-mm-ddthhmmss-sssssssz-format

**Comment by AbtinZohrabi** [comment]
It is true and make sense but I have no idea why other services returning with this format which is not being able to be parsed by rometools. 
This problem is happening in these cases that you want to parse such formats.

**Comment by mishako** [comment]
You could add this format to your `rome.properties` file. Simply add `datetime.extra.masks=yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSS'Z'` and place the file in `src/main/resources`.

It will still yield wrong result, because `SSSSSSSSS` will be interpreted as milliseconds, but it's better than nothing. We could try get rid of `SimpleDateFormat` to make date formatting more flexible, but I would rather spend time on Rome 2.

I will close your PR because this format work in an unexpected way by overflowing the milliseconds into seconds etc.
